
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://iconix.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl:

# Google tracking id

google-tracking-id: "UA-101920397-1"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Nadja Rhodes"
title: "{ Nadja Rhodes }"
description: "Nadja Rhodes is a software developer and aspiring data scientist. I like to code for the web, and I blog (mainly) as I learn to tell stories with data. Opinions expressed are mine."
keywords: "rhodes, nadja, software, development, data, science, analytics, code, web, stanford, microsoft"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/cover-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: False
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 60000
lines: # You can add HTML Tags in the Text
  - text: "Do something today that your future self will thank you for."
  - text: "An investment in knowledge pays the best interest."
  - text: "Better late than never."
  - text: "Everyone you will ever meet knows something that you don't."
  - text: "If we are facing in the right direction, all we have to do is keep on walking."
  - text: "The new multitasking: procrastinating on many things at once."
  - text: "Same old slippers. Same old rice. Same old glimpse of paradise."
  - text: "Without deviation from the norm, progress is not possible."
  - text: "You don't have to see the whole staircase. Just take the first step."

me-img: "/img/allo-moji1.png"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 84

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: False
tumblr-share: False
pinterest-share: False
pocket-share: True
disqus-shortname: "iconix-github-io"
vkontakte-share: False

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/enterHH_uk.gif"
    date: "2004-2007"
    description: '<a href="https://en.wikipedia.org/wiki/Habbo">Habbo UK</a> made me internet (from Maryland)'
  - image: "/img/timeline/baracktocat.jpg"
    date: "Fall 2008"
    description: "Started coding in earnest for my senior year of high school; accepted into Stanford University, Class of 2013!"
  - image: "/img/timeline/effectivecplusplus.jpg"
    date: "Summer 2011"
    description: "First summer in Seattle; during Google internship, read Effective C++ and became charmed by design patterns"
  - image: "/img/timeline/prefixspan.png"
    date: "Summer 2012"
    description: 'Dove deep into <a href="https://en.wikipedia.org/wiki/PrefixSpan">Sequential Pattern Mining</a> at a <a href="http://www.kecl.ntt.co.jp/rps/index.html">research facility</a> internship in Japan'
  - image: "/img/timeline/summersonic.jpg"
    date: "August 18-19, 2012"
    description: 'Attended first #LiveMusic festival: <a href="http://www.summersonic.com/2012/">Summer Sonic</a> in Osaka, Japan'
  - image: "/img/timeline/stanford.png"
    date: "Spring 2013"
    description: 'Senior year: <a href="http://cs142.stanford.edu/">CS 142</a> (with the <a href="https://www.quora.com/What-are-the-most-profound-life-lessons-from-Stanford-Professor-John-Ousterhout">legendary</a> Prof. John Ousterhout) and <a href="http://cs210.stanford.edu/">CS 210</a> solidified my enthusiasm for web development; my 210 senior <a href="https://github.com/iconix/atc">project</a> took me to SAP HQ in Walldorf, Germany'
  - image: "/img/timeline/onenote2013.png"
    date: "June 2013"
    description: "Graduated Stanford... with a job at Microsoft!"
  - image: "/img/timeline/bumbershoot.jpg"
    date: "August 31, 2013"
    description: 'Attended <a href="https://www.bumbershoot.com">Bumbershoot</a> in Seattle #LiveMusic'
  - image: "/img/timeline/ng_ml.png"
    date: "Summer 2014"
    description: 'Second summer in Seattle; completed <a href="https://www.coursera.org/learn/machine-learning">Andrew Ng&#39;s Machine Learning</a> course in June (<a href="/notes/2017/07/03/ng-ml-notes.html">notes</a>)'
  - image: "/img/timeline/sasquatch.jpg"
    date: "May 22-25, 2015"
    description: 'Attended <a href="https://www.sasquatchfestival.com/">Sasquatch</a> at the Gorge, WA #LiveMusic'
  - image: "/img/timeline/github.png"
    date: "2013~2016"
    description: 'My side projects centered around "big"-data-for-news ideas (<a href="http://thetechmblog.blogspot.com/">The Tech Machine</a>; <a href="https://github.com/iconix/tn">Trending News</a>), building off of my PrefixSpan experience in Japan; meanwhile, the <a href="https://github.com/OneNoteDev/WebClipper/wiki">best parts of my career</a> centered around the web'
  - image: "/img/timeline/labtocat.png"
    date: "May 7, 2017"
    description: "Started this blog to dive deeper into data products!"
  - image: "/img/timeline/paradiso.png"
    date: "June 23-24, 2017"
    description: 'Attended <a href="http://paradisofestival.com/">Paradiso</a> at the Gorge, WA #LiveMusic'
  - image: "/img/timeline/adventurecat.png"
    date: "Today"
    description: 'Adventure Time! (<a href="https://github.com/iconix/resume/blob/master/latex/datascience/resume.pdf">resume</a>)'

# First image of the Timeline
timeline-img: "/img/allo-moji2.png"

###########
# Contact #
###########

email: "narhodes1+blog@gmail.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: 'Nadja does not particularly enjoy <a href="/#about">writing about herself</a>.'
author_blurb_image: "/img/allo-moji3.png"

##################
# Social Buttons #
##################

social:
  - title: "linkedin"
    url: "https://www.linkedin.com/in/nadjarhodes/"
  - title: "github"
    url: "https://github.com/iconix"
  - title: "rss"
    url: "/feed.xml"
  - title: "envelope"
    url: "narhodes1+blog@gmail.com"
  - title: "lastfm"
    url: "https://www.last.fm/user/iconix"

############
# 404 page #
############

err-404-img: "/img/labtocat.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  Blog: 'latest-post'
  About: 'about'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
